{
	"openapi": "3.0.0",
	"components": {
		"examples": {},
		"headers": {},
		"parameters": {},
		"requestBodies": {},
		"responses": {},
		"schemas": {
			"TsoaResponse_string_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"type": "string"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"TsoaResponse_any_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ErrorResponse": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"properties": {
							"data": {
								"nullable": true
							},
							"reason": {
								"type": "string",
								"nullable": true
							},
							"errorCode": {
								"type": "string"
							}
						},
						"type": "object"
					},
					"success": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			}
		},
		"securitySchemes": {}
	},
	"info": {
		"title": "myform_reform",
		"version": "1.0.0",
		"license": {
			"name": "ISC"
		},
		"contact": {}
	},
	"paths": {
		"/project": {
			"get": {
				"operationId": "SetTest",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/TsoaResponse_string_"
								}
							}
						}
					}
				},
				"tags": [
					"project node CRUD"
				],
				"security": [],
				"parameters": []
			}
		},
		"/auth/sms/send": {
			"post": {
				"operationId": "SendSms",
				"responses": {
					"200": {
						"description": "SMS 전송 완료",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/TsoaResponse_any_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"statusCode": 200,
												"message": "SMS 전송이 완료되었습니다."
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "입력값 유효성 검증 실패",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_001",
												"reason": "입력 형식이 올바르지 않습니다.",
												"data": "유효하지 않은 전화번호 형식입니다. 입력받은 전화번호 : 0101234"
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"429": {
						"description": "인증 시도 횟수 초과",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_004",
												"reason": "인증 코드 입력 시도 횟수를 초과했습니다.",
												"data": "blockedAt: 2026-01-10T16:01:30.523Z, availableAt: 2026-01-10T16:31:30.523Z"
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "서버 내부 오류 (SMS 발송 또는 Redis 저장 실패)",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_002",
												"reason": "SMS 전송 중 오류가 발생했습니다.",
												"data": "SOLAPI API 요청 실패 : ${error.message}"
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_003",
												"reason": "Redis에 인증 정보 저장 중 오류가 발생했습니다.",
												"data": "Redis 저장 실패 : ${error.message}"
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"properties": {
									"phoneNumber": {
										"type": "string"
									}
								},
								"required": [
									"phoneNumber"
								],
								"type": "object"
							}
						}
					}
				}
			}
		},
		"/auth/sms/verify": {
			"post": {
				"operationId": "VerifySms",
				"responses": {
					"200": {
						"description": "인증 코드 검증 성공",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/TsoaResponse_any_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"statusCode": 200,
												"message": "인증이 성공적으로 완료되었습니다."
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "인증 코드 형식 오류 또는 만료 또는 부재 또는 일치하지 않음",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_005",
												"reason": "인증 코드가 만료되었거나 존재하지 않습니다.",
												"data": "입력하신 인증 코드가 만료되었거나 존재하지 않습니다."
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_006",
												"reason": "인증 코드가 일치하지 않습니다.",
												"data": "인증 코드가 일치하지 않습니다."
											},
											"success": null
										}
									},
									"Example 3": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_001",
												"reason": "입력 형식이 올바르지 않습니다.",
												"data": "유효하지 않은 인증 코드 형식입니다. 입력받은 인증 코드 : 1234567"
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"429": {
						"description": "인증 시도 횟수 초과",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_004",
												"reason": "인증 코드 입력 시도 횟수를 초과했습니다.",
												"data": "blockedAt: 2026-01-10T16:01:30.523Z, availableAt: 2026-01-10T16:31:30.523Z"
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "서버 내부 오류 (인증 코드 검증 실패)",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "Auth_999",
												"reason": "인증 코드 검증 중 오류가 발생했습니다.",
												"data": "인증 중 알 수 없는 오류가 발생했습니다."
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"tags": [
					"Auth"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"properties": {
									"phoneNumber": {
										"type": "string"
									},
									"code": {
										"type": "string"
									}
								},
								"required": [
									"phoneNumber",
									"code"
								],
								"type": "object"
							}
						}
					}
				}
			}
		}
	},
	"servers": [
		{
			"url": "/"
		}
	]
}